# Use an official Node.js runtime as the base image
FROM node:19-alpine3.16

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . /app

# Build the React application
RUN npm run build

# Serve the built files with a web server
CMD ["npm", "start"]